# snakemake -j1 --notemp --use-conda -np
# snakemake --forceall --rulegraph | dot -Tpdf > docs/ancestry.pdf

HM3: "/sc/arion/projects/LOAD/shea/bin/ldsc/w_hm3_cpra.snplist"
DATAOUT: "output"
SAMPLE: ["gsa1234567", "201711_CoreExome-DIAN_flipped", "all_chrall_filtered_flipped"]
REFNAME: ["1kG"]
tgped: "data/reference/20130606_g1k.ped"
GenoMiss: 0.05
kb: 50
size: 10
r2: 0.1
SampMiss: 0.05
MAF: 0.01
HWE: 10e-30
BUILD: ["hg19"]
METHOD: ['projected', 'unsupervised']
